#!/usr/bin/env python3
"""Bake the shipwreck's shop thumbnails (2026-10-10), one per theme, the jellyfish's way;
--check verifies the tracked outputs are what this script makes."""
from pathlib import Path
import sys,io
from gen_theme_assets import raster,array
root=Path(__file__).resolve().parent.parent
# wood, dark wood, hole, sand, metal, sail, water tint - per theme
PAL=[('original',  '#8a6440','#4a3524','#0b1a22','#2e3b2c','#6f7577','#d8cfb0','#0a3c46'),
     ('quiet-lagoon','#7a7d64','#3e4a3c','#0e1816','#6f7a66','#6d7872','#c9c7a8','#386a63'),
     ('tidepool-club','#b38a5c','#6a4b30','#1c1e2a','#c5ad84','#8a8578','#efe3c3','#b7b488')]
def svg(wood,dark,hole,sand,metal,sail,water):
    return f'''<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32">
<ellipse cx="16" cy="29" rx="14" ry="2.2" fill="{sand}"/>
<path d="M4 17 Q6 27 16 27 Q26 27 28 15 L26 14 Q24 25 16 25 Q8 25 6 16 Z" fill="{dark}"/>
<path d="M5 16 Q7 25 16 25 Q25 25 27 14 L4 14 Z" fill="{wood}"/>
<path d="M4 14 L27 14 L28 15 L4.5 15.5 Z" fill="{dark}"/>
<path d="M5 18 L26 18 M6.5 21.5 L24 21.5" stroke="{dark}" stroke-width=".7"/>
<ellipse cx="11" cy="19.5" rx="2.6" ry="2.2" fill="{hole}"/><ellipse cx="20" cy="19" rx="2.1" ry="1.9" fill="{hole}"/>
<rect x="15" y="3" width="1.6" height="11.5" fill="{dark}"/><rect x="11" y="6" width="9" height="1" fill="{dark}"/>
<path d="M12 7 L15 7 L15 12 Z" fill="{sail}"/>
<path d="M26 13 L27.5 7" stroke="{metal}" stroke-width=".8" stroke-dasharray="1 .8"/>
<path d="M28.5 4.5 v6 M26.5 7.5 h4 M26 10.5 q2.5 2.5 5 0" stroke="{metal}" stroke-width="1.1" fill="none" stroke-linecap="round"/>
<circle cx="28.5" cy="3.8" r="1" fill="none" stroke="{metal}" stroke-width=".8"/>
<circle cx="7" cy="9" r=".8" fill="{water}" opacity=".7"/><circle cx="9" cy="5.5" r="1.1" fill="{water}" opacity=".6"/>
</svg>'''
outputs={};code=['/* Generated by tools/gen_wreck_assets.py (2026-10-10). Do not edit. */\n#include "icons.h"\n']
for i,(name,*cols) in enumerate(PAL):
    base=root/'assets/themes'/name; s=svg(*cols)
    outputs[base/'shop_wreck.svg']=(s+'\n').encode()
    im=raster(s.encode(),32,32);buf=io.BytesIO();im.save(buf,format='PNG');outputs[base/'shop_wreck.png']=buf.getvalue()
    pixels=list(im.getdata());rgb=[((r>>3)<<11)|((g>>2)<<5)|(b>>3) for r,g,b,a in pixels];alpha=[a for r,g,b,a in pixels]
    symbol='icon_shop_wreck' if not i else f'wreck_icon_{i}'
    code.extend([array(symbol+'_rgb','uint16_t',rgb),array(symbol+'_a','uint8_t',alpha),f'{"static " if i else ""}const icon_t {symbol}={{32,32,{symbol}_rgb,{symbol}_a}};\n'])
code.append('const icon_t *wreck_theme_icon(int theme){return theme==1?&wreck_icon_1:theme==2?&wreck_icon_2:&icon_shop_wreck;}\n')
outputs[root/'common/wreck_assets.c']='\n'.join(code).encode()
for p,data in outputs.items():
    if '--check' in sys.argv: assert p.read_bytes()==data,f'Stale asset: {p}'
    else: p.parent.mkdir(parents=True,exist_ok=True);p.write_bytes(data)
print('Verified wreck icons' if '--check' in sys.argv else 'Generated 3 wreck SVG/PNG icons and common/wreck_assets.c')
